import {currentUser} from '@/lib/auth';import {redirect} from 'next/navigation';import Shell from '@/components/Shell';import {db} from '@/lib/db';import {revalidatePath} from 'next/cache';import {publicCardUrl} from '@/lib/codes';import QrPdfExport from '@/components/QrPdfExport';
const labels:Record<string,string>={AVAILABLE:'Disponible',IN_REGISTRATION:'En registro',ACTIVE:'Activa',DISABLED:'Deshabilitada',REPLACED:'Reemplazada'};
type SP={q?:string;batch?:string;status?:string;group?:string};
export default async function Page({searchParams}:{searchParams:SP}){const u=await currentUser();if(!u)redirect('/login');if(u.role!=='ADMIN')redirect('/vendedor');
 async function update(fd:FormData){'use server';const me=await currentUser();if(!me||me.role!=='ADMIN')return;const id=String(fd.get('id')),status=String(fd.get('status'));const destinationUrl=String(fd.get('destinationUrl')||'').trim()||null;const old=await db.card.findUnique({where:{id}});if(!old)return;await db.card.update({where:{id},data:{status,destinationUrl}});if(destinationUrl&&destinationUrl!==old.destinationUrl)await db.urlHistory.create({data:{cardId:id,oldUrl:old.destinationUrl,newUrl:destinationUrl,changedBy:me.id}});revalidatePath('/admin/tarjetas')}
 const q=searchParams.q?.trim()||'';const batch=searchParams.batch||'';const status=searchParams.status||'';const group=searchParams.group==='batch';
 const batches=await db.batch.findMany({orderBy:{createdAt:'desc'},select:{id:true,name:true,createdAt:true,_count:{select:{cards:true}}}});
 const cards=await db.card.findMany({where:{AND:[q?{OR:[{code:{contains:q}},{businessName:{contains:q}},{representative:{contains:q}},{destinationUrl:{contains:q}},{seller:{name:{contains:q}}},{seller:{email:{contains:q}}}]}:{},batch?{batchId:batch}:{},status?{status}:{}]},include:{batch:true,seller:true},orderBy:[{batchId:'desc'},{createdAt:'desc'}],take:500});
 const exportCards=cards.map(c=>({id:c.id,code:c.code,businessName:c.businessName,batchId:c.batchId,batchName:c.batch?.name||null}));
 const grouped=group?Array.from(cards.reduce((m,c)=>{const k=c.batchId||'none';if(!m.has(k))m.set(k,{name:c.batch?.name||'Sin lote',cards:[] as typeof cards});m.get(k)!.cards.push(c);return m},new Map<string,{name:string;cards:typeof cards}>()).values()):[];
 const table=(items:typeof cards)=><div className="tableWrap"><table><thead><tr><th>QR / Código</th><th>Lote</th><th>Negocio / Responsable</th><th>Vendedor</th><th>Estado / Destino</th></tr></thead><tbody>{items.length?items.map(c=><tr key={c.id}><td><div className="qrCell"><img src={`/api/qr/${c.code}`} alt="QR"/><div><b>{c.code}</b><small>{publicCardUrl(c.code)}</small></div></div></td><td>{c.batch?.name||'—'}</td><td><b>{c.businessName||'—'}</b><small className="cellSub">{c.representative||'Sin responsable'}</small></td><td>{c.seller?<><b>{c.seller.name}</b><small className="cellSub">{c.seller.email}</small></>:'—'}</td><td><form action={update} className="inlineEdit"><input type="hidden" name="id" value={c.id}/><select name="status" defaultValue={c.status}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="destinationUrl" defaultValue={c.destinationUrl||''} placeholder="https://..."/><button>Guardar</button></form></td></tr>):<tr><td colSpan={5} className="muted">No hay tarjetas con estos filtros.</td></tr>}</tbody></table></div>;
 return <Shell title="Tarjetas" user={u} active="cards"><div className="pageHead"><div><span className="eyebrow">INVENTARIO</span><h1>Tarjetas</h1><p>Encuentra, separa por lote y exporta exactamente las tarjetas que necesitas.</p></div><a className="primaryBtn" href="/admin/generar">+ Generar lote</a></div><section className="panel">
  <form className="cardFilters"><div className="filterSearch"><label>Buscar</label><input className="input" name="q" defaultValue={q} placeholder="Código, negocio, responsable, URL o vendedor..."/></div><div><label>Lote</label><select name="batch" defaultValue={batch}><option value="">Todos los lotes</option>{batches.map(b=><option key={b.id} value={b.id}>{b.name} ({b._count.cards})</option>)}</select></div><div><label>Estado</label><select name="status" defaultValue={status}><option value="">Todos</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><label className="groupCheck"><input type="checkbox" name="group" value="batch" defaultChecked={group}/> Agrupar por lote</label><button className="primaryBtn">Aplicar filtros</button><a className="ghostBtn filterClear" href="/admin/tarjetas">Limpiar</a></form>
  <div className="filterSummary"><b>{cards.length}</b> tarjeta{cards.length===1?'':'s'} encontradas{batch&&<span> · lote seleccionado</span>}{q&&<span> · búsqueda “{q}”</span>}</div>
  <QrPdfExport cards={exportCards}/>
  {group?grouped.map(g=><div className="batchGroup" key={g.name}><div className="batchGroupHead"><div><span className="eyebrow">LOTE</span><h2>{g.name}</h2></div><span>{g.cards.length} tarjetas</span></div>{table(g.cards)}</div>):table(cards)}
 </section></Shell>}
