'use client';
import {useMemo,useState} from 'react';

type CardItem={id:string;code:string;businessName:string|null;batchId:string|null;batchName:string|null};
type PaperKey='A4'|'LETTER'|'LEGAL'|'A3'|'A5'|'CUSTOM';
const papers:Record<Exclude<PaperKey,'CUSTOM'>,{label:string,w:number,h:number}>={
 A4:{label:'A4 — 210 × 297 mm',w:210,h:297}, LETTER:{label:'Carta — 215.9 × 279.4 mm',w:215.9,h:279.4},
 LEGAL:{label:'Legal/Oficio — 215.9 × 355.6 mm',w:215.9,h:355.6}, A3:{label:'A3 — 297 × 420 mm',w:297,h:420}, A5:{label:'A5 — 148 × 210 mm',w:148,h:210},
};
export default function QrPdfExport({cards}:{cards:CardItem[]}){
 const [size,setSize]=useState('30'),[paper,setPaper]=useState<PaperKey>('A4'),[customW,setCustomW]=useState('210'),[customH,setCustomH]=useState('297'),[busy,setBusy]=useState(false),[tick,setTick]=useState(0);
 const batches=useMemo(()=>Array.from(new Map(cards.filter(c=>c.batchId).map(c=>[c.batchId!,c.batchName||'Sin nombre'])).entries()),[cards]);
 const selected=()=>Array.from(document.querySelectorAll<HTMLInputElement>('input[name="cardSelect"]:checked')).map(x=>x.value);
 const count=typeof document==='undefined'?0:selected().length; void tick;
 function setChecks(ids:string[],checked=true){const wanted=new Set(ids);document.querySelectorAll<HTMLInputElement>('input[name="cardSelect"]').forEach(x=>{if(wanted.has(x.value))x.checked=checked});setTick(v=>v+1)}
 function selectAll(){const boxes=Array.from(document.querySelectorAll<HTMLInputElement>('input[name="cardSelect"]'));const should=boxes.some(x=>!x.checked);boxes.forEach(x=>x.checked=should);setTick(v=>v+1)}
 const sizeNum=Number(size),validSize=Number.isFinite(sizeNum)&&sizeNum>=10&&sizeNum<=100;
 async function download(){const ids=selected();if(!ids.length){alert('Selecciona al menos una tarjeta.');return}if(!validSize)return;setBusy(true);const p=paper==='CUSTOM'?{w:Number(customW),h:Number(customH)}:papers[paper];if(!p||!Number.isFinite(p.w)||!Number.isFinite(p.h)||p.w<50||p.h<50){alert('Revisa el tamaño de hoja.');setBusy(false);return}try{const r=await fetch('/api/export/qr-pdf',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids,qrSizeMm:sizeNum,pageWidthMm:p.w,pageHeightMm:p.h,paper})});if(!r.ok)throw new Error(await r.text());const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='qr-seleccion.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){alert('No se pudo generar el PDF. '+(e instanceof Error?e.message:''))}finally{setBusy(false)}}
 async function remove(){const ids=selected();if(!ids.length){alert('Selecciona al menos una tarjeta.');return}if(!confirm(`¿Eliminar definitivamente ${ids.length} tarjeta${ids.length===1?'':'s'}? Esta acción no se puede deshacer.`))return;setBusy(true);try{const r=await fetch('/api/cards/delete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids})});if(!r.ok)throw new Error(await r.text());location.reload()}catch(e){alert('No se pudieron eliminar. '+(e instanceof Error?e.message:''));setBusy(false)}}
 return <div className="exportBar v9"><div><b>Acciones sobre tarjetas</b><span>Selecciona tarjetas directamente en la tabla de abajo. Puedes exportarlas o eliminarlas en grupo.</span></div><label>Lado del QR <span><input inputMode="decimal" value={size} onChange={e=>setSize(e.target.value.replace(/[^0-9.]/g,''))} onBlur={()=>{if(!validSize)setSize('30')}}/> mm</span></label><label>Tamaño de hoja <select value={paper} onChange={e=>setPaper(e.target.value as PaperKey)}>{Object.entries(papers).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}<option value="CUSTOM">Personalizada</option></select></label>{paper==='CUSTOM'&&<div className="customPaper"><label>Ancho mm<input value={customW} onChange={e=>setCustomW(e.target.value.replace(/[^0-9.]/g,''))}/></label><label>Alto mm<input value={customH} onChange={e=>setCustomH(e.target.value.replace(/[^0-9.]/g,''))}/></label></div>}<div className="selectionActions"><button type="button" className="ghostBtn" onClick={selectAll}>Seleccionar todas</button>{batches.length>0&&<select defaultValue="" onChange={e=>{if(e.target.value){setChecks(cards.filter(c=>c.batchId===e.target.value).map(c=>c.id));e.currentTarget.value=''}}}><option value="">Seleccionar lote…</option>{batches.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>}<button type="button" className="primaryBtn" disabled={busy||!validSize} onClick={download}>{busy?'Procesando…':`Exportar seleccionadas${count?` (${count})`:''}`}</button><button type="button" className="ghostBtn dangerBtn" disabled={busy} onClick={remove}>Eliminar seleccionadas{count?` (${count})`:''}</button></div></div>
}
